# Quadratic Formula

## Estimate a Square Root

::: {.rmdthink}

Can you estimate the irrational numbers $\sqrt{2}$, $\sqrt{3}$, $\sqrt{5}$ and $\sqrt{7}$ without using a calculator?

Can you estimate the square root $\sqrt{m^2+n}$, where $m$ and $n$ are positive integers?

:::

## Completing the Square

**The square root property**:\
Suppose that $X^2=d$. Then $X=\sqrt{d}$ or $X=-\sqrt{d}$, or simply $X=\pm\sqrt{d}$.

The square root property provides another method to solve a quadratic equation, completing the square. This method is based on the following observations:
$$
x^2+{\mathbf{b}}x+{\mathbf{\left(\frac b2\right)^2}}=\left(x+{\mathbf{\frac b2}}\right)^2,
$$
and more generally, let $f(x)=ax^2+bx+c$, and $h=-\frac{b}{2a}$, then
$$
ax^2+bx+c=a(x-h)^2+f(h)=a\left(x+\frac{b}{2a}\right)^2+\frac{4ac-b^2}{4a^2}.
$$

The procedure to rewrite a trinomial as the sum of a perfect square and a constant is called ***completing the square***.

:::{.example}

Solve the equation $x^2+2x-1=0$.

:::

:::{.solution}
\

1. Isolate the constant.
    $$x^2+2x=1$$
2. With $b=2$, add $\left(\frac 22\right)^2$ to both sides to complete a square for the binomial $x^2+bx$.
    $$
    \begin{aligned}
        x^2+2x+\left(\frac22\right)^2&=1+\left(\frac22\right)^2\\\
        \left(x+\frac22\right)^2&=1+1\\
        (x+1)^2&=2\\
    \end{aligned}
    $$
3. Solve the resulting equation using the square root property.
    $$
    \begin{aligned}
        x+1 =\sqrt2    & \qquad\text{or} & x+1 =-\sqrt2   \\
        x   =-1+\sqrt2 & \qquad\text{or} & x   =-1-\sqrt2
    \end{aligned}
    $$

Note that the solution can also be written as $x=-1\pm\sqrt2$.

:::

:::{.example}

Solve the equation $-2x^2+8x-9=0$.

:::

:::{.solution}
\

1. Isolate the constant.
    $$-2x^2+8x=9$$
1. Divide by $-2$ to rewrite the equation in $x^2+Bx=C$ form
    $$x^2-4x=-\frac{9}{2}$$
1. With $b=-4$, add $\left(\frac{-4}{2}\right)^2=4$ to both sides to complete the square for the binomial $x^2-4x$.
    $$
    \begin{aligned}
        x^2-4x+4&=-\frac{9}{2}+4\\\
        (x-2)^2&=-\frac{1}{2}
    \end{aligned}
    $$
1. Solve the resulting equation and simplify.
    $$
    \begin{aligned}
        x-2 =\frac{\ii}{\sqrt{2}}    & \qquad\text{or} & x-2 =-\frac{\ii}{\sqrt{2}}   \\
        x   =2+\frac{\sqrt{2}}{2}\ii & \qquad\text{or} & x   =2-\frac{\sqrt{2}}{2}\ii
    \end{aligned}
    $$

:::

::: {.rmdtip}

Another way to complete the square is to use the formula $ax^2+bx+c=a(x-h)^2+f(h)$, where $f(h)=ah^2+bh+c$ is the value of the polynomial $ax^2+bx+c$ at $x=h$.

:::

## The Quadratic Formula

Using the method of completing the square, we obtain the follow quadratic formula for the quadratic equation $ax^2+bx+c=0$ with $a\neq 0$:
$$
    x=\dfrac{-b\pm\sqrt{b^2-4ac}}{2a}.
$$

The quantity $b^2-4ac$ is called the ***discriminant*** of the quadratic equation.

1. If $b^2-4ac>0$, the equation has two real solutions.
1. If $b^2-4ac=0$, the equation has one real solution.
1. If $b^2-4ac<0$, the equation has two imaginary solutions (no real solutions).

:::{.example}

Determine the type and the number of solutions of the equation $(x-1)(x+2)=-3$.

:::

:::{.solution}
\

1. Rewrite the equation in the form $ax^2+bx+c=0$.
    $$
        \begin{aligned}
            (x-1)(x+2)&=-3\\
            x^2+x+1&=0
        \end{aligned}
    $$
1. Find the values of $a$, $b$ and $c$.
    $$
        a=1, b=1 ~\text{and}~ c=1.
    $$
1. Find the discriminant $b^2-4ac$.
    $$
        b^2-4ac=1^2-4\cdot 1\cdot 1=-3.
    $$

The equation has two imaginary solutions.

:::

:::{.example}

Solve the equation $2x^2-4x+7=0$.

:::

:::{.solution}
\

1. Find the values of $a$, $b$ and $c$.
    $$
        a=2, b=-4 ~\text{and}~ c=7.
    $$
1. Find the discriminant $b^2-4ac$.
    $$
        b^2-4ac=(-4)^2-4\cdot 2\cdot 7=16-56=-40.
    $$
1. Apply the quadratic formula and simplify.
    $$
    \begin{aligned}
        x=&\dfrac{-b\pm\sqrt{b^2-4ac}}{2a}\\
        =&\dfrac{-(-4)\pm\sqrt{-40}}{2\cdot 2}\\
        =&\frac{4\pm 2\sqrt{10} \ii}{4}\\
        =&1\pm\frac{\sqrt{10}}{2}\ii.
    \end{aligned}
    $$

:::

:::{.example}

Find the base and the height of a **triangle** whose base is three inches more than twice its height and whose area is $5$ square inches. Round your answer to the nearest tenth of an inch.

:::

:::{.solution}
\

1. We may suppose the height is $x$ inches. The base can be expressed as $2x+3$ inches.
1. By the area formula for a triangle, we have an equation.
    $$\frac12 x(2x+3)=5.$$
1. Rewrite the equation in $ax^2+bx+c=0$ form.
    $$
        \begin{aligned}
            x(2x+3)&=10\\
            2x^2+3x-10&=0.
        \end{aligned}
    $$
1. By the quadratic formula, we have
    $$
    x=\frac{-3\pm\sqrt{3^2-4\cdot 2\cdot (-10)}}{2\cdot 2}=\frac{-3\pm \sqrt{89}}{4}.
    $$

Since $x$ can not be negative, $x=\frac{-3+\sqrt{89}}{4}\approx 1.6$ and $2x+3\approx 6.2$.
The height and base of the triangle are approximately $1.6$ inches and 6.2 inches respectively.

:::

\newpage

## Practice

:::{.exercise}

Solve the quadratic equation by the square root property.

1. $2x^2-6=0$
2. $(x-3)^2=10$
3. $4(x+1)^2+25=0$

:::

:::{.exercise}

Solve the quadratic equation by completing the square.

1. $x^2+x-1=0$
2. $x^2+8x+12=0$
3. $3x^2+6x-1=0$

:::

:::{.exercise}

Determine the number and the type of solutions of the given equation.

1. $x^2+8x+3=0$
1. $3x^2-2x+4=0$
1. $2x^2-4x+2=0$

:::

:::{.exercise}

Solve using the quadratic formula.

1. $x^2+3x-7=0$
2. $2x^2=-4x+5$
3. $2x^2=x-3$

:::

:::{.exercise}

Solve using the quadratic formula.

1. $(x-1)(x+2)=3$
1. $2x^2-x=(x+2)(x-2)$
1. $\frac12 x^2+x= \frac13$

:::

:::{.exercise}

A **triangle** whose area is $7.5$ square meters has a base that is one meter less than triple the height. Find the length of its base and height. Round to the nearest hundredth of a meter.

:::

:::{.exercise}

A **rectangular** garden whose length is $2$ feet longer than its width has an area 66 square feet. Find the dimensions of the garden, rounded to the nearest hundredth of a foot.

:::
