# Rational Equations

## A Problem of the Father of Algebra

::: {.rmdthink}

The father of algebra, [Muḥammad ibn Musa al-Khwarizmi](https://en.wikipedia.org/wiki/Muhammad_ibn_Musa_al-Khwarizmi#Algebra), in his book "[Algebra](https://archive.org/details/algebraofmohamme00khuwrich/page/44/mode/2up)", answered the following problem:

>  "... I have divided ten into two parts; and have divided the first by the second, and the second by the first, and the sum of the quotient is two and one-sixth;..."

Do you know what are those two parts?

:::

## Solving Rational Equations

A ***rational equation*** is an equation that contains a rational expression. One way to solve rational equations is to clear all denominators by multiplying the LCD to both sides. Note that because there are values such that the LCD has the value zero. Clearing denominator in general is not an equivalent transformation, rather a functional transformation. So don't forget to check possible extraneous solutions.

```{example}

Solve
$$
\dfrac{5}{x^2-9}=\dfrac{3}{x-3}-\dfrac{2}{x+3}.
$$

```

```{solution}
\

1. Find the LCD.
    Since $x^2-9=(x+3)(x-3)$, the LCD is $(x+3)(x-3)$.
2. Clear denominators.
    Multiply each rational expression in both sides by $(x+3)(x-3)$ and simplify:
    $$
        \begin{aligned}
            (x+3)(x-3)\cdot\dfrac{5}{x^2-9}&=(x+3)(x-3)\cdot\dfrac{3}{x-3}-(x+3)(x-3)\cdot\dfrac{2}{x+3}\\
            5&=3(x+3)-2(x-3)
        \end{aligned}
    $$
3. Solve the resulting equation.
    $$
        \begin{aligned}
            5&=3(x+3)-2(x-3)
            5&=x+15\\
            -10&=x
        \end{aligned}
    $$
4. Check for any extraneous solution by plugging the solution into the LCD to see if it is zero. If it is zero, then the solution is extraneous.
    $$
        (-10+3)(-10-3)\neq 0
    $$
    So $x=-10$ is a valid solution of the original equation.

```

::: {.rmdtip}

**Reduction With Auxiliary Conditions**  
Clearing denominator uses the strategy "**reduction with auxiliary conditions**". The auxiliary condition used when clearing the denominators is that the LCD is non-zero. Generally, if you don't know how to solve a problem under the given condition, you may try solve the problem by adding extra conditions first and then try to eliminate the extra conditions and/or their consequences.

:::

## Literal Equations

A ***literal equation*** is an equation involving two or more variables. When solving a literal equation for one variable, other variables can be viewed as constants.

```{example}

Solve for $x$ from the equation
$$
\frac{1}{x}+\frac{1}{y}=\dfrac{1}{z}.
$$

```

```{solution}
\

1. The LCD is $xyz$.
1. Clear denominators.
    $$
        \begin{aligned}
            xyz\cdot\frac{1}{x}+xyz\cdot\frac{1}{y}&=xyz\cdot\dfrac{1}{z}\\
            yz+xz&=xy\\
        \end{aligned}
    $$
1. Solve the resulting equation.
    $$
        \begin{aligned}
            yz+xz&=xy\\
            yz&=xy-xz\\
            yz&=x(y-z)\\
            \dfrac{yz}{y-z}&=x \quad \text{if} y\neq z
        \end{aligned}
    $$
1. The solution is $x=\dfrac{yz}{y-z}$ if $y\neq z$. If $y=z$, the equation has no solution.

```

::: {.rmdnote}

Another way to solve a rational equation is to rewrite and simplify the equation into the form $\dfrac{\text{A}}{B}=0$ where $\dfrac{A}{B}$ is a **reduced fraction**. Then the rational equation is equivalent to the equation $A=0$.

:::

\newpage

## Practice

```{exercise}

Solve.

1. $\dfrac1{x+1}+\dfrac1{x-1}=\dfrac4{x^2-1}$
2. $\dfrac{30}{x^2-25}=\dfrac3{x+5}+\dfrac2{x-5}$

```

```{exercise}

Solve.

1. $\dfrac{2x-1}{x^2+2x-8}=\dfrac1{x-2}-\dfrac{2}{x+4}$
1. $\dfrac{3x}{x-5}=\dfrac{2x}{x+1}-\dfrac{42}{x^2-4x-5}$

```

```{exercise}

Solve a variable from a formula.

1. Solve for $f$ from\quad $\dfrac1p+\dfrac1q=\dfrac1f$.
1. Solve for $x$ from\quad $A=\dfrac{f+cx}{x}$.

```

```{exercise}

Solve for $x$ from the equation.

1. $2(x+1)^{-1}+x^{-1}=2$.
1. $\displaystyle\frac{a^2x +2a}{x^{-1}}=-1$.

```

```{exercise}

David can row 3 miles per hour in still water. It takes him 90 minutes to row 2 miles upstream and then back. How fast is the current?

```

```{exercise}

The size of a A0 paper is defined to have an area of 1 square meter with the longer dimension $\sqrt[4]{2}$ meters. Successive paper sizes in the series A1, A2, A3, and so forth, are defined by halving the preceding paper size across the larger dimension. Can you find the dimension of a A4 paper?

```
