# Rational Functions

## The Law of Lever

::: {.rmdthink}

 > “Give me a fulcrum and a place to stand, I will move the world.” by [Archimedes of Syracuse](https://en.wikipedia.org/wiki/Archimedes#Mathematics)

 In volume I of his book "On the Equilibrium of Planes", Archimedes proved that magnitudes are in equilibrium at distances reciprocally proportional to their weights. See the video [Law of the Lever](https://youtu.be/yhrR4384SGE?t=8) on youtube for an animated explanation.

Suppose there is a infinite long lever with a load 100 newton that is placed 1 meters away the fulcrum, the pivoting point.

- Can you find the force needed to balance the load in terms of the distance away from the fulcrum?
- How much force will be needed if it is place 5 meters away from the fulcrum?

:::

## The Domain of a Rational Function

A ***rational function*** $f$ is defined by an equation $f(x)=\frac{p(x)}{q(x)}$, where $p(x)$ and $q(x)$ are polynomials and the degree of $q(x)$ is at least one. Since the denominator cannot be zero, the domain of $f$ consists all real numbers except the numbers such that $q(x)=0$

:::{example}

Find the domain of the function $f(x)=\frac{1}{x-1}$.

:::

:::{solution}
\

Solve the equation $x-1=0$, we get $x=1$. Then the domain is $\{x\mid x\neq 1\}$. In interval notation, the domain is
$$
(-\infty, 1)\cup (1,\infty).
$$

:::

:::{example}

Suppose that the cost in dollars to produce x toy cars is given by C(x)=5,000+5x. How many toy cars would the factory have to produce in order for the average production cost $10 per item?

:::

:::{solution} 

The average cost is defined as
$$A(x)=\frac{C(x)}{x}.$$
The number of toy cars should be produced to get the average cost $10 is the solution of the equation $A(x)=10$, that is
$$
\begin{aligned}
    \frac{5000+5x}{x}&=10\\
    5000+5x&=10x\\
    5000&=5x\\
    x&=1000.
\end{aligned}
$$

The factory should produce 1000 toy cars for the average cost $10 per item.

:::

\newpage

## Practice

:::{exercise}

Find the domain of each function. Write in interval notation.

1. $f(x)=\frac{x^2}{x-2}$
1. $f(x)=\frac{x}{x^2-1}$
1. $f(x)=\sqrt{2x-3}$
1. $f(x)=\sqrt{x^2+1}$\hfill\null

:::
