# Radical Functions

## Speed of a Tsunami

::: {.rmdthink}

A [tsunami](https://en.wikipedia.org/wiki/Tsunami) is generally referred to is a series of waves on the ocean caused by earthquakes or other events that cause sudden displacements of large volumes of water. In ideal situation, the velocity $v$ of a wave at where the water depth is $d$ meters is approximately
$$
v=\sqrt{9.8d}.
$$
The wave will slow down when closer to the coast but will be higher.

Suppose a tsunami was caused by earthquake somewhere 10000 meters away the coast of California. The depth of the water where the tsunami was generated is 5000 meter.

- What's the initial speed of the tsunami?
- What's the speed of the tsunami at where the water depth is 2000.
- Suppose the speed wouldn't decrease, how long it takes the tsunami reach the coast?

:::

## The Domain of a Radical Function

A ***radical function*** $f$ is defined by an equation $f(x)=\sqrt[n]{r(x)}$, where $r(x)$ is an algebraic expression.  For example $f(x)=\sqrt{x+1}$. When $n$ is odd number, $r(x)$ can be any real number.  When $n$ is even, $r(x)$ has to be nonnegative, that is $r(x)\geq 0$ so that $f(x)$ is a real number.

:::{.example}

Find the domain of the function $f(x)=\sqrt{x+1}$.

:::

:::{.solution}
\

Since the index is $2$ which is even, the function has real outputs only if the radicand $x+1\geq 0$.
Solve the inequality, we get $x\geq -1$. In interval notation, the domain is
$$
[-1,\infty).
$$

:::

:::{.example}

For a pendulum clock, the period T of the pendulum is approximately modeled by the following function of the length L of the pendulum:
$$T=2\sqrt{L}$$
where $L$ and $T$ are measured in meters and seconds respectively.

- If the length of the pendulum is 4 meters, what is the period?
- If the period of a pendulum clock is 1 second, how long should be the pendulum?

:::

:::{.solution}

- Because the length of the pendulum is 4 meters, that is $L=4$. Then the period is $T=2\cdot\sqrt{4}=4$ seconds.
- Because the period of the pendulum is 1 second, that is $T=1$. Then the length $L$ is the solution of the equations $2\sqrt{L}=1$.
  $$\begin{aligned}
      2\sqrt{L}&=1\\
      \sqrt{L}&=\frac12\\
      L&=\left(\frac12\right)^2\\
      L&=\frac14.
  \end{aligned}
  $$
  So the length of the pendulum should be 1/4 in so that the period is 1 second.

:::

\newpage

## Practice

:::{.exercise}

Find the domain of each function. Write in interval notation.

1. $f(x)=1-\frac{2x}{x+3}$
1. $f(x)=\frac{x-2}{x^2-4}$
1. $f(x)=\sqrt{1-x^2}$
1. $f(x)=-\sqrt{\frac{1}{x-5}}$

:::
